//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tymetrix.T360.Mobile.Client.AppWP8.Resources.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tymetrix.T360.Mobile.Client.AppWP8.Resources.Culture.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Failure..
        /// </summary>
        internal static string A100 {
            get {
                return ResourceManager.GetString("A100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect network. Enable network connection and try again..
        /// </summary>
        internal static string APP005 {
            get {
                return ResourceManager.GetString("APP005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process the request due to network error..
        /// </summary>
        internal static string APP006 {
            get {
                return ResourceManager.GetString("APP006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server encounter an error unable to process the request..
        /// </summary>
        internal static string APP007 {
            get {
                return ResourceManager.GetString("APP007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server could not be found but may be available again in the future..
        /// </summary>
        internal static string APP008 {
            get {
                return ResourceManager.GetString("APP008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request did not succeed..
        /// </summary>
        internal static string APP200 {
            get {
                return ResourceManager.GetString("APP200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Encryption..
        /// </summary>
        internal static string APP800 {
            get {
                return ResourceManager.GetString("APP800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during Decryption..
        /// </summary>
        internal static string APP801 {
            get {
                return ResourceManager.GetString("APP801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed..
        /// </summary>
        internal static string APP900 {
            get {
                return ResourceManager.GetString("APP900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        internal static string APP901 {
            get {
                return ResourceManager.GetString("APP901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the last person in the review route and you do not have an authorization amount high enough to approve it. Please contact your administrator..
        /// </summary>
        internal static string ApproveError {
            get {
                return ResourceManager.GetString("ApproveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company is disabled..
        /// </summary>
        internal static string COMPANY_IS_DISABLED {
            get {
                return ResourceManager.GetString("COMPANY_IS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member must accept the network Confidentiality Disclaimer. Please contact your network administrator..
        /// </summary>
        internal static string CONFIDENTIALITY_DISCLAIMER {
            get {
                return ResourceManager.GetString("CONFIDENTIALITY_DISCLAIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to Invoices Awaiting My Review. Please contact your network administrator..
        /// </summary>
        internal static string HAS_INVOICELIST_ACCESS {
            get {
                return ResourceManager.GetString("HAS_INVOICELIST_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password..
        /// </summary>
        internal static string INCORRECT_LOGIN_PASSWORD {
            get {
                return ResourceManager.GetString("INCORRECT_LOGIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate integrated login. Contact your company administrator for details..
        /// </summary>
        internal static string INCORRECT_SSO_LOGIN {
            get {
                return ResourceManager.GetString("INCORRECT_SSO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This invoice cannot be approved because the Minimum Number of Reviewers setting has not been met. Please contact your T360 Administrator..
        /// </summary>
        internal static string InsufficientNumberOfReviewers {
            get {
                return ResourceManager.GetString("InsufficientNumberOfReviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to T360° Mobile. Please contact your network administrator..
        /// </summary>
        internal static string INVOICE001 {
            get {
                return ResourceManager.GetString("INVOICE001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TyMetrix 360 mobile is not configured for Law Firm or Vendor use at this time. We look forward to adding this functionality and we will notify you when these features have been added..
        /// </summary>
        internal static string INVOICE002 {
            get {
                return ResourceManager.GetString("INVOICE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter narrative text..
        /// </summary>
        internal static string INVOICE003 {
            get {
                return ResourceManager.GetString("INVOICE003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action type is empty. Unable to fetch the reasons..
        /// </summary>
        internal static string INVOICE004 {
            get {
                return ResourceManager.GetString("INVOICE004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action type is invalid. Unable to fetch the reasons..
        /// </summary>
        internal static string INVOICE005 {
            get {
                return ResourceManager.GetString("INVOICE005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reason..
        /// </summary>
        internal static string INVOICE006 {
            get {
                return ResourceManager.GetString("INVOICE006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select adjustment mode..
        /// </summary>
        internal static string INVOICE007 {
            get {
                return ResourceManager.GetString("INVOICE007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter adjustment amount..
        /// </summary>
        internal static string INVOICE008 {
            get {
                return ResourceManager.GetString("INVOICE008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select adjustment type..
        /// </summary>
        internal static string INVOICE009 {
            get {
                return ResourceManager.GetString("INVOICE009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select adjustment style..
        /// </summary>
        internal static string INVOICE010 {
            get {
                return ResourceManager.GetString("INVOICE010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net total is empty..
        /// </summary>
        internal static string INVOICE011 {
            get {
                return ResourceManager.GetString("INVOICE011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Item Id is empty..
        /// </summary>
        internal static string INVOICE012 {
            get {
                return ResourceManager.GetString("INVOICE012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Invoice..
        /// </summary>
        internal static string INVOICE013 {
            get {
                return ResourceManager.GetString("INVOICE013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Line Item..
        /// </summary>
        internal static string INVOICE014 {
            get {
                return ResourceManager.GetString("INVOICE014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Access..
        /// </summary>
        internal static string INVOICE015 {
            get {
                return ResourceManager.GetString("INVOICE015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to Invoices Awaiting My Review. Please contact your network administrator..
        /// </summary>
        internal static string INVOICE016 {
            get {
                return ResourceManager.GetString("INVOICE016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the proper access to view invoices. Please contact your network administrator..
        /// </summary>
        internal static string INVOICE017 {
            get {
                return ResourceManager.GetString("INVOICE017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the proper access to approve invoice. Please contact your network administrator..
        /// </summary>
        internal static string INVOICE018 {
            get {
                return ResourceManager.GetString("INVOICE018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxed and Adjusted invoices cannot be Approved..
        /// </summary>
        internal static string INVOICE019 {
            get {
                return ResourceManager.GetString("INVOICE019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the proper access to adjust invoice. Please contact your network administrator..
        /// </summary>
        internal static string INVOICE020 {
            get {
                return ResourceManager.GetString("INVOICE020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the proper access to reject invoice. Please contact your network administrator..
        /// </summary>
        internal static string INVOICE021 {
            get {
                return ResourceManager.GetString("INVOICE021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This invoice contains taxes and cannot be adjusted..
        /// </summary>
        internal static string INVOICE022 {
            get {
                return ResourceManager.GetString("INVOICE022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative Invoice balance is not allowed..
        /// </summary>
        internal static string INVOICE023 {
            get {
                return ResourceManager.GetString("INVOICE023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current invoice doesn&apos;t belong to reviewer’s queue..
        /// </summary>
        internal static string INVOICE024 {
            get {
                return ResourceManager.GetString("INVOICE024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Positive Credit Note balance is not allowed..
        /// </summary>
        internal static string INVOICE025 {
            get {
                return ResourceManager.GetString("INVOICE025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Credit Note(s) result in a negative balance of the original invoice. Please edit and resubmit..
        /// </summary>
        internal static string INVOICE026 {
            get {
                return ResourceManager.GetString("INVOICE026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TyMetrix 360 mobile is not configured for Law Firm or Vendor use at this time. We look forward to adding this functionality and we will notify you when these features have been added..
        /// </summary>
        internal static string ISCLIENT_TYMETRIXUSER {
            get {
                return ResourceManager.GetString("ISCLIENT_TYMETRIXUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last used network is disabled..
        /// </summary>
        internal static string LAST_USED_NETWORK_IS_DISABLED {
            get {
                return ResourceManager.GetString("LAST_USED_NETWORK_IS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the license agreement by log-in to the desktop version of T360 and try again..
        /// </summary>
        internal static string LICENSE_AGREEMENT {
            get {
                return ResourceManager.GetString("LICENSE_AGREEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is invalid. Unable to adjust the line item..
        /// </summary>
        internal static string LINEITEM001 {
            get {
                return ResourceManager.GetString("LINEITEM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have proper access to adjust the line item. Please contact your network You do not have proper access to adjust the line item. Please contact your network administrator..
        /// </summary>
        internal static string LINEITEM002 {
            get {
                return ResourceManager.GetString("LINEITEM002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have proper access to adjust the selected line item. Please contact your network administrator..
        /// </summary>
        internal static string LINEITEM003 {
            get {
                return ResourceManager.GetString("LINEITEM003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have proper access to reject the line item. Please contact your network administrator..
        /// </summary>
        internal static string LINEITEM004 {
            get {
                return ResourceManager.GetString("LINEITEM004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have proper access to reject the selected line item. Please contact your network administrator..
        /// </summary>
        internal static string LINEITEM005 {
            get {
                return ResourceManager.GetString("LINEITEM005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have proper access to undo the line item. Please contact your network administrator..
        /// </summary>
        internal static string LINEITEM006 {
            get {
                return ResourceManager.GetString("LINEITEM006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot adjust by an amount greater than the smallest amount in the selected line item.
        /// </summary>
        internal static string LINEITEM007 {
            get {
                return ResourceManager.GetString("LINEITEM007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Line Item contains taxes and cannot be adjusted..
        /// </summary>
        internal static string LINEITEM008 {
            get {
                return ResourceManager.GetString("LINEITEM008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot adjust by an amount greater than the smallest selected line item..
        /// </summary>
        internal static string LINEITEM009 {
            get {
                return ResourceManager.GetString("LINEITEM009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username..
        /// </summary>
        internal static string LOGIN001 {
            get {
                return ResourceManager.GetString("LOGIN001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password..
        /// </summary>
        internal static string LOGIN002 {
            get {
                return ResourceManager.GetString("LOGIN002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Integrated Login Id..
        /// </summary>
        internal static string LOGIN003 {
            get {
                return ResourceManager.GetString("LOGIN003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Id is empty..
        /// </summary>
        internal static string LOGIN004 {
            get {
                return ResourceManager.GetString("LOGIN004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceOS is empty..
        /// </summary>
        internal static string LOGIN005 {
            get {
                return ResourceManager.GetString("LOGIN005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceType is empty..
        /// </summary>
        internal static string LOGIN006 {
            get {
                return ResourceManager.GetString("LOGIN006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version is empty..
        /// </summary>
        internal static string LOGIN007 {
            get {
                return ResourceManager.GetString("LOGIN007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This invoice cannot be approved. %.
        /// </summary>
        internal static string MatterSpendValidationError {
            get {
                return ResourceManager.GetString("MatterSpendValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your member account is disabled..
        /// </summary>
        internal static string MEMBER_IS_DISABLED {
            get {
                return ResourceManager.GetString("MEMBER_IS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your member account is locked. Contact your company administrator for details..
        /// </summary>
        internal static string MEMBER_IS_LOCKED {
            get {
                return ResourceManager.GetString("MEMBER_IS_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client is not approved..
        /// </summary>
        internal static string PRELOGIN001 {
            get {
                return ResourceManager.GetString("PRELOGIN001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application session expired. Please login to continue..
        /// </summary>
        internal static string PRELOGIN002 {
            get {
                return ResourceManager.GetString("PRELOGIN002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload data received from the client is empty..
        /// </summary>
        internal static string PRELOGIN003 {
            get {
                return ResourceManager.GetString("PRELOGIN003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password needs to be reset, please log into the desktop version of T360 to change your password..
        /// </summary>
        internal static string REQUEST_PASSWORD_RESET {
            get {
                return ResourceManager.GetString("REQUEST_PASSWORD_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password needs to be reset, please log into the desktop version of T360 to change your password..
        /// </summary>
        internal static string RESET_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        internal static string RESET_PWD001 {
            get {
                return ResourceManager.GetString("RESET_PWD001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        internal static string RESET_PWD002 {
            get {
                return ResourceManager.GetString("RESET_PWD002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New and confirm passwords must match..
        /// </summary>
        internal static string RESET_PWD003 {
            get {
                return ResourceManager.GetString("RESET_PWD003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review route policy violation detected.  You cannot approve the invoice this time. Please contact your administrator..
        /// </summary>
        internal static string RouteError {
            get {
                return ResourceManager.GetString("RouteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application session timed out. Please login to continue..
        /// </summary>
        internal static string SessionTimedOut {
            get {
                return ResourceManager.GetString("SessionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxed and Adjusted invoices cannot be Approved..
        /// </summary>
        internal static string TaxedAdjustedInvoice {
            get {
                return ResourceManager.GetString("TaxedAdjustedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is not associated with any active networks and therefore can not be logged into the system..
        /// </summary>
        internal static string THERE_IS_NOT_NETWORK {
            get {
                return ResourceManager.GetString("THERE_IS_NOT_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has expired, please log into the desktop version of T360 to change your password..
        /// </summary>
        internal static string TOO_SIMPLE_PASSWORD {
            get {
                return ResourceManager.GetString("TOO_SIMPLE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred during the process..
        /// </summary>
        internal static string UNKNOWN_EXCEPTION {
            get {
                return ResourceManager.GetString("UNKNOWN_EXCEPTION", resourceCulture);
            }
        }
    }
}
